name: Deploy Laravel App

on:
  push:
    branches:
      - main

env:
  APP_DIR: /domains/karcianka.albertmazur.pl/public_html/
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_USER: ${{ secrets.USER }}
  SSH_HOST: ${{ secrets.HOST }}
  BRANCH: "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Deploy to Server
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
        chmod 600 private_key

        # Wysyłanie plików na serwer
        rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -i private_key" \
        --exclude '.env' --exclude 'storage/' --exclude 'vendor/' --exclude 'node_modules/' \
        ./ $SSH_USER@$SSH_HOST:$APP_DIR

        # Uruchomienie komend po wdrożeniu
        ssh -o StrictHostKeyChecking=no -i private_key $SSH_USER@$SSH_HOST << 'EOF'
          cd $APP_DIR
          composer install --no-dev --optimize-autoloader
          php artisan migrate --force
          php artisan cache:clear
          php artisan config:clear
          php artisan route:clear
          php artisan view:clear
          php artisan config:cache
          php artisan queue:restart
          sudo systemctl restart nginx
        EOF
