name: Deploy Laravel App
on:
  push:
    branches:
      - main
env:
  APP_DIR: "/domains/karcianka.albertmazur.pl/public_html"
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_USER: "amazurpriv"
  SSH_HOST: ${{ secrets.HOST }}
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key
    - name: Deploy Laravel
      run: |
        rsync -avz --delete -e "ssh -i private_key" ./ $SSH_USER@$SSH_HOST:$APP_DIR
        ssh -i private_key $SSH_USER@$SSH_HOST << EOF
          cd $APP_DIR
          composer install --no-dev --optimize-autoloader
          php artisan migrate --force
          php artisan cache:clear
          php artisan config:cache
          php artisan queue:restart
          sudo systemctl restart nginx
        EOF
    - name: Clean up
      run: rm -f private_key
