name: Deploy Laravel App

on:
  push:
    branches:
      - main

env:
  GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
  DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Deploy Laravel
      run: |
        cd $DEPLOY_PATH
        git pull https://$GITHUB_PAT@github.com/albertmazur/karcianka-multiplayer.git main
        composer install --no-dev --optimize-autoloader
        npm install
        npm run build
        php artisan migrate --force
        php artisan cache:clear
        php artisan config:cache
