name: Deploy Laravel App
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Deploy to Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_USER: ${{ secrets.USER }}
        SSH_HOST: ${{ secrets.HOST }}
        APP_DIR: /domains/karcianka.albertmazur.pl/public_html/
      run: |
        # Utworzenie katalogu SSH
        mkdir -p ~/.ssh
        
        # Zapis klucza prywatnego
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        
        # Dodanie klucza do known_hosts
        ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
        
        # Synchronizacja plików
        rsync -avz --delete \
        -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" \
        --exclude '.env' \
        --exclude 'storage/' \
        --exclude 'vendor/' \
        --exclude 'node_modules/' \
        --exclude '.git/' \
        ./ $SSH_USER@$SSH_HOST:$APP_DIR
        
        # Wykonanie zdalnych poleceń
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'
          cd /domains/karcianka.albertmazur.pl/public_html/
          composer install --no-dev --optimize-autoloader
          php artisan migrate --force
          php artisan cache:clear
          php artisan config:clear
          php artisan route:clear
          php artisan view:clear
          php artisan config:cache
          php artisan queue:restart
          sudo systemctl restart nginx
        EOF
