name: Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Deploy Laravel
      run: |
        cd ~/domains/karcianka.albertmazur.pl/public_html || exit 1
        git pull origin main
        git pull origin main
        composer install --no-dev --optimize-autoloader
        php artisan migrate --force
        php artisan cache:clear
        php artisan config:cache
        php artisan queue:restart
        sudo systemctl restart nginx
